### PR TITLE
Add missing support for headerdoc comments

### PR DESCRIPTION
**Pull request by warren-gavin**
Headerdoc comments (comments starting with `/**`) are not supported in the syntax parser.

I had to change the logic of the `containsBalancedOccurrences` method in `Segment.swift` in order to correctly balance the comments.

An opening comment `/*` or opening headerdoc comment `/**` can both be balanced out by the same closing comment token `*/`, so `containsBalancedOccurrences` was extended to take an array of possible tokens, rather than individual ones.

Now the segments will be marked as comments if they contain balanced instances of either `/*` or `/**` with instances of `*/`

For testing I found failures were really hard to track down because the equality was over an array of components and it was hard to see which component was failing. So I've separated out each test for equality over individual components.

### CODE REVIEW

**Comment by MaciejGad** [comment]
Hi @warren-gavin, I've also fixed this problem in my PR #24, but it looks like the project is abandoned and there is no-one to review and merge PR ;(

**Comment by warren-gavin** [comment]
Hi @MaciejGad 

yes, I saw your PR after I created mine, and there's even a third with the same issue. I think they all have merit in terms of adding more unit tests, at least 😄 

I don't think this is entirely abandoned, I know @JohnSundell is travelling a lot and I don't think Splash is a high priority as it seems to be mostly complete for it's intended purpose. But I showed him an extension applying Splash to terminal highlighting (PR #29) and he seemed interested in including it, so we might see some movement at a later date.

**Comment by JohnSundell** [comment]
It’s definitely not abandoned. Splash is in active use and I definitely want to keep improving it. Just haven’t been able to prioritize reviewing these PRs yet. But will very soon. Sorry about the delay and I really appreciate your contributions.

**Comment by JohnSundell** [comment]
Thanks a lot @warren-gavin, and to @MaciejGad, @marcocapano and everyone else who has worked on this issue. I really appreciate your contributions a lot. I did, however, end up doing a slightly different implementation to solve this problem, which you can find here: #47. Since `CommentRule` was the only rule using the `containsBalancedOccurrences` API, it could now be removed - which let me make a simpler implementation by inlining all of the required logic. Thanks a lot anyway to all of you, closing this one now.

**Comment by JohnSundell** [comment]
And again sorry about the delays, and for giving you the impression that this was abandoned. Splash is used for every single article on Swift by Sundell, so it's a project that's incredibly important to me. I just haven't been able to find the time needed to review PRs and give good feedback on them - but I'm currently re-organizing my open source work a bit, so hopefully I'll be able to be more responsive in the future.

**Pull request closed without merging**
