### PR TITLE
Support 0x2700ff and 0b100_0101

### PR DESCRIPTION
**Pull request by hfossli**

### CODE REVIEW

**Comment by hfossli** [comment]
Good point! I'll update my pr

**Comment by JohnSundell** [comment]
Thanks @hfossli 🎉

**Comment by JohnSundell** [comment]
Also @hfossli, could you add tests that exercises any new code paths you'll add? Check the existing tests if you need some inspiration 🙂

**Comment by JohnSundell** [comment]
Closed due to inactivity. Please re-open if this issue is still relevant 👍

**Pull request closed without merging**
