### PR TITLE
Adding rethrows support

### PR DESCRIPTION
**Pull request by marcocapano**
This PR adds support (and related test) for the "rethrows" keyword.

### CODE REVIEW

**Comment by marcocapano** [comment]
I only have some doubts about the test's naming. The current name is `testFunctionWithRethrows`, maybe It's ok, but it doesn't feel "right" 😅

**Comment by JohnSundell** [comment]
@marcocapano Could you rebase this with `master` and solve the conflicts? Then I'll review 😄

**Comment by JohnSundell** [comment]
And about the name, how about `testRethrowingFunctionDeclaration`?

**Comment by marcocapano** [comment]
> And about the name, how about `testRethrowingFunctionDeclaration`?

Feels better, thanks!

As for the conflicts, I guess I messed up😂 I'll fix

**Pull request closed without merging**
