### PR TITLE
Improving guide on how to add a new grammar (and add Objective-C support)

### PR DESCRIPTION
**Pull request by marcocapano**
I'm currently working on an `ObjectiveCGrammar` type to add support for Objective-C syntax highlighting. I think Objective-C should be the first language to be added since a lot of blogs out there that write about Swift also provide Objective-C code samples. 

Here the question: how should one proceed and structure tests? All tests are about Swift, so I'm not sure about where/how should I put my tests about this new type.
Impoving the Contributing Guide here could both answer my question and help other who might want to add a new type conforming to `Grammar` .

I'm already working on basic support for standard statements (for, while, if, switch) so hopefully I'll be ready to submit the first PR with a basic Objective-C support soon after I understand how to proceed with tests.

### CODE REVIEW

**Comment by marcocapano** [comment]
@JohnSundell I see that every test case inherits from SyntaxHighlighterTestCase

```swift
/// Test case used as an abstract base class for all tests relating to
/// syntax highlighting. For all such tests, the Swift grammar is used.
class SyntaxHighlighterTestCase: SplashTestCase {
```

Should this new test cases for Objective-C too?
That comments says it uses only Swift Grammar. Does this mean I don't reuse all the logic you wrote in the "Core" group?

**Comment by JohnSundell** [comment]
Awesome to hear that you're working on an Objective-C grammar @marcocapano! While I'd be happy to link to it from Splash's README, it's not something that I'd like to be included in this repo. I don't wish to take on the maintenance responsibility for it, since I don't use Objective-C anymore.

So feel free to build it in whichever way you want (I'd suggest taking a similar approach to Splash itself, and write as many tests as you can that verify the outcome of highlighting a given piece of code). Since Splash is a Swift Package, depending on it in your own grammar repo will be super easy. Just add it as a dependency in your `Package.swift` file.

Then, once you're done, feel free to submit a PR to Splash that adds a link to your repo in the README. Note that I'd like for your grammar to be somewhat complete and have high quality in order for me to link to it.

Does that answer your question? 🙂

**Comment by marcocapano** [comment]
It sure does, thanks John!

**Comment by JohnSundell** [comment]
Great! Can we close this?

**Pull request closed without merging**
