### PR TITLE
Add support for new keywords

### PR DESCRIPTION
**Pull request by marcocapano**
This PR introduces the following keywords in SwiftGrammar:

- continue
- fallthrough
- repeat

**UPDATE:**
- while

### CODE REVIEW

**Comment by JohnSundell** [comment]
Hi @marcocapano, thanks a lot for this contribution 😄 Would be awesome if you could add some tests that verifies your fix. See the other tests for reference, and let me know if you need some help 👍

**Comment by marcocapano** [comment]
Sure!

**Comment by marcocapano** [comment]
Shoud I create a new test or change the testSwitchStatement in StatementTests?

**Comment by JohnSundell** [comment]
Create new tests. For example `testSwitchStatementWithFallthrough`, and so on for the other keywords 🙂 Just to make sure they keep being highlighted correctly as we iterate on Splash 👍

**Comment by marcocapano** [comment]
Perfect, I’m on it. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcocapano** [comment]
@JohnSundell how should I run the tests?

**Comment by marcocapano** [comment]
Since there's no xcodeproj I'm not sure how I should run the tests. Committing and waiting for Travis to give a response is slowing down the workflow, hope someone can help.

**Comment by JohnSundell** [comment]
Regarding running tests, you can generate an Xcode project for Splash by using:
```
swift package generate-xcodeproj
```
Or if you want a shorter version, you can install [my script](https://gist.github.com/JohnSundell/6f372850dc763cb5960fe45b91abd646) that lets you do just:
```
spm xcode
```

**Comment by JohnSundell** [comment]
@marcocapano You don't have to worry about it, as it's git ignored 🙂

**Comment by marcocapano** [comment]
Nice! Didn’t check gitignore😅 
Thanks for taking the time to review and merge this! 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
