### PR TITLE
Adding nonmutating support

### PR DESCRIPTION
**Pull request by marcocapano**
This PR adds support for the `nonmutating` keyword and a related test. Even if not used a lot, it is still part of the language so I thought this would be a good addition.

### CODE REVIEW

**Comment by marcocapano** [comment]
Good! May I ask why #49 makes this fail?

**Comment by JohnSundell** [comment]
@marcocapano Because I've turned on SwiftLint on the CI, and this branch doesn't have a SwiftLint config 🙂

**Comment by marcocapano** [comment]
Thanks!

**Comment by warren-gavin** [comment]
@marcocapano @JohnSundell 
There is a stead drip feed of keywords that were originally missed out. Swift's keywords are all defined here: https://docs.swift.org/swift-book/ReferenceManual/LexicalStructure.html#ID413

I think it would make sense to create a PR for all of these in one go and reduce the work required. I'm happy to do that tonight

**Comment by JohnSundell** [comment]
@warren-gavin I'd recommend adding one keyword per PR, big PRs tend to take me forever to review, because it's super hard for me to slot those reviews into my day. With many small PRs I can quickly take one whenever I have 5 minutes over 🙂 But yeah, PRs adding support for missing keywords are more than welcome 👍

**Comment by warren-gavin** [comment]
@JohnSundell Understood, I just hope @marcocapano doesn't do all the work before I get a change to help 😁

**Comment by marcocapano** [comment]
hahah please feel free to contribute, I'm not here to block people from helping! I'll be glad to see a PR from you😊

**Comment by JohnSundell** [comment]
Yeah same, I'm now also able to dedicate some time every other day to reviewing PRs, so hopefully we can establish a smooth workflow around all this 👍

**Comment by warren-gavin** [comment]
Not sure if the right thing to do is to continue posting comments to a closed ticket, but I've no code with which to create a PR yet, so here goes:

`nonmutating` and `dynamic` are special case keywords according to the Swift docs. They are "keywords reserved in particular contexts", so it's possible for them to be both a keyword and a variable. 

The others are:
associativity, convenience, didSet, final, get, infix, indirect, lazy, left, mutating, none, optional, override, postfix, precedence, prefix, Protocol, required, right, set, Type, unowned, weak, and willSet

Even `let unowned = 42` is allowed!

As Splash is mostly used for snippets for blogs, teaching etc it's probably bad form for content authors to use any of the above as variable names in their examples, so I guess it's probably better to stick to treating them as keywords only. But I'd be interested in other opinions. What do you think @JohnSundell @marcocapano ?

**Comment by marcocapano** [comment]
Being able to tell whether they are used as identifiers or keywords would be great, but like you said this is probably something not that urgent 😊

**Comment by JohnSundell** [comment]
@warren-gavin Right, I think Splash should already take care of most of those cases (but not sure about those two in particular), since I've had instances in my articles where I've named a function `get` for example, which Splash initially highlighted as a keyword - but has since been fixed in #36.

Splash needs to operate using a "best guess" approach, so in the case of `let unowned = 42`, I think it should treat `unowned` as plain text, rather than as a keyword.

**Comment by JohnSundell** [comment]
Feel free to open a draft PR with this if you want to discuss it further btw 🙂

**Pull request merged**
